trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

resources:
- repo: self

variables:
  dockerfilePath: 'Aspnetcoreapp/Dockerfile'
  imageName: 'xdealboo/phxtraining'


stages:
- stage: Build_and_Push
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build_and_Push_Job
    displayName: 'Build Image'
    pool:
      name: PHX
    steps:    
    - task: CmdLine@2
      inputs:
       script: 'docker build -f $(dockerfilePath) -t $(imageName) .'
       workingDirectory: '$(Build.SourcesDirectory)/Docker-compose-dotnet-core-and-mssql'
    - task: Docker@2
      inputs:
        containerRegistry: 'MY_DOCKER_HUB'
        repository: 'xdealboo/phxtraining'
        command: 'push'
        tags: |
          $(Build.BuildId)
          $(Build.SourceVersion)
          latest
