trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

resources:
- repo: self

variables:
  dockerfilePath: 'Aspnetcoreapp/Dockerfile'
  imageName: 'xdealboo/phxtraining'


stages:
- stage: Build_and_Push
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build_and_Push_Job
    displayName: 'Build Image'
    pool:
      name: PHX
    steps:    
      - task: Docker@2
        inputs:
          containerRegistry: 'MY_DOCKER_HUB'
          repository: 'xdealboo/phxtraining'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Docker-compose-dotnet-core-and-mssql/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: PHX
    steps:
     - checkout: self
     - task: Bash@3
       displayName: Update Docker Compose file and deploy
       inputs:
         targetType: 'inline'
        inputs:
        targetType: 'inline'
        script: |
          sed -i 's|image:.*$|image: $(containerRegistry)/xdealboo/phxtraining:$(Build.BuildId)|g' $(Build.SourcesDirectory)/Docker-compose-dotnet-core-and-mssql/docker-compose.yml
          docker-compose -f $(Build.SourcesDirectory)/Docker-compose-dotnet-core-and-mssql/docker-compose.yml up -d
    env:
      containerRegistry: 'MY_DOCKER_HUB'd
