trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

resources:
- repo: self

variables:
  dockerfilePath: 'Docker-compose-dotnet-core-and-mssql/Aspnetcoreapp/Dockerfile'
  imageName: 'xdealboo/phxtraining:002'

stages:
- stage: Build_and_Push
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build_and_Push_Job
    displayName: 'Build and Push Docker Image'
    pool:
      name: PHX
    steps:    
    - task: CmdLine@2
      inputs:
       script: 'docker build -f $(dockerfilePath) -t $(imageName) .'